import { eurosToCents } from '@/lib/domain/money'
import type { Property } from '@/lib/domain/types'
import { DATA_QUALITY_FLAGS } from '@/lib/domain/data-quality'

type SeedInput = {
  id: string
  address: string
  locality: string
  province: string
  cadastralRef: string | null
  purchaseEuros: number
  valuationEuros: number | null
  salePriceEuros: number | null
  status: Property['status']
  details: string | null
  notes?: string | null
  dataQuality?: Property['dataQuality']
}

function build(input: SeedInput): Property {
  return {
    id: input.id,
    address: input.address,
    locality: input.locality,
    province: input.province,
    cadastralRef: input.cadastralRef,
    purchaseCostCents: eurosToCents(input.purchaseEuros),
    valuationCents: input.valuationEuros === null ? null : eurosToCents(input.valuationEuros),
    salePriceCents: input.salePriceEuros === null ? null : eurosToCents(input.salePriceEuros),
    status: input.status,
    details: input.details,
    notes: input.notes ?? null,
    dataQuality: input.dataQuality ?? [],
  }
}

// Sources:
// - Hernán's PDF "Valoraciones a 27-04-2026 activos comprados (Black Cesars 2) 25.pdf" — 25 activos comprados
// - CSV image passed by user — 28 propiedades (25 comprados + 3 pendientes de compra)
// When sources disagree, the PDF wins for purchased assets (commercial source of truth)
// and the discrepancy is exposed via dataQuality flags.

export const FONDO_2_PROPERTIES: Property[] = [
  build({
    id: 'F2-MAD1-1',
    address: 'Calle Doña Irene 9',
    locality: 'El Boalo',
    province: 'Madrid',
    cadastralRef: '0097417VL2009N0001PQ',
    purchaseEuros: 231_391,
    valuationEuros: 420_000,
    salePriceEuros: 450_000,
    status: 'en_proceso_desocupacion',
    details: 'Adosado · 205 m² (77 m² aparcamiento sótano + 59 m² planta baja + 59 m² planta 1ª + 10 m² buhardilla) · 1996',
  }),
  build({
    id: 'F2-MAD2-2',
    address: 'Calle Ministriles 5, Esc. Int., 1º Izq.',
    locality: 'Madrid',
    province: 'Madrid',
    cadastralRef: '0538826VK4703H0013TD',
    purchaseEuros: 130_900,
    valuationEuros: 210_000,
    salePriceEuros: 220_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 40 m² vivienda + 6 m² áreas comunes · 1 hab · 1 baño · sin ascensor',
  }),
  build({
    id: 'F2-MAD3-3',
    address: 'Calle San Bonet 5, 1º Izq.',
    locality: 'Madrid',
    province: 'Madrid',
    cadastralRef: '5298624VK3659G0020YZ',
    purchaseEuros: 140_000,
    valuationEuros: 205_000,
    salePriceEuros: 220_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 63 m² vivienda + 4 m² áreas comunes · 2 hab · 1 baño · sin ascensor · 1967',
    notes: 'PZ Armilla 1. Testigo: https://www.idealista.com/inmueble/110543530/',
    dataQuality: [DATA_QUALITY_FLAGS.addressMismatchSanBorjaBonet],
  }),
  build({
    id: 'F2-MAD4-4',
    address: 'Calle Ramón Serrano 51, Subsuelo A',
    locality: 'Madrid',
    province: 'Madrid',
    cadastralRef: '6708501VK3760H0001MA',
    purchaseEuros: 94_350,
    valuationEuros: 145_000,
    salePriceEuros: 150_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 51 m² vivienda · 2 hab · 1 baño · sin ascensor · 1963',
  }),
  build({
    id: 'F2-MAD5-5',
    address: 'Calle de la Perdiz 4',
    locality: 'Onda',
    province: 'Castellón',
    cadastralRef: '4075809YK3247E0001XJ',
    purchaseEuros: 19_198,
    valuationEuros: 35_000,
    salePriceEuros: 41_000,
    status: 'en_proceso_desocupacion',
    details: '41 m² planta baja + 41 m² 1ª + 41 m² almacén 2ª · construcción 1900',
    notes: 'Testigo: https://www.idealista.com/inmueble/111010685/',
    dataQuality: [DATA_QUALITY_FLAGS.localityMismatchPerdiz],
  }),
  build({
    id: 'F2-MAL1-6',
    address: 'Calle Calerito 10, 8º G',
    locality: 'Málaga',
    province: 'Málaga',
    cadastralRef: '9925203UF6692N0038BD',
    purchaseEuros: 160_000,
    valuationEuros: 205_000,
    salePriceEuros: 210_000,
    status: 'desocupado',
    details: 'Piso · 81 m² vivienda · 3 hab · 2 baños · con ascensor · 1970',
  }),
  build({
    id: 'F2-MAL2-7',
    address: 'Calle Jorge de Montemayor 4',
    locality: 'Málaga',
    province: 'Málaga',
    cadastralRef: '3968104UF7636N0001TK',
    purchaseEuros: 102_828,
    valuationEuros: 240_000,
    salePriceEuros: 260_000,
    status: 'en_proceso_desocupacion',
    details: 'Adosado · 123 m² vivienda · 3 hab · 1 baño · 1960',
  }),
  build({
    id: 'F2-MAL3-8',
    address: 'Calle Ebro 10, Esc. 1, 2º D',
    locality: 'Málaga',
    province: 'Málaga',
    cadastralRef: '2272203UF7627S0012PQ',
    purchaseEuros: 47_330,
    valuationEuros: 95_000,
    salePriceEuros: 110_000,
    status: 'desocupado',
    details: 'Piso · 80 m² vivienda + 19 m² áreas comunes · 3 hab · 2 baños · sin ascensor · 1975',
    notes: 'Palma - Palmilla. Zona conflictiva por okupas.',
  }),
  build({
    id: 'F2-MAL4-9',
    address: 'Calle Cabriel 29, Esc. 1, 9º D',
    locality: 'Málaga',
    province: 'Málaga',
    cadastralRef: '2472202UF7627S0036EL',
    purchaseEuros: 42_427,
    valuationEuros: 110_000,
    salePriceEuros: 120_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 105 m² vivienda · 3 hab · 2 baños · con ascensor · 1975',
    notes: 'Zona de gitanos. Defendibilidad del precio depende de okupación del edificio y vecinos.',
    dataQuality: [DATA_QUALITY_FLAGS.addressMismatchGabrielCabriel],
  }),
  build({
    id: 'F2-MAL5-10',
    address: 'Calle Ebro 3, Esc. 1, 1º C',
    locality: 'Málaga',
    province: 'Málaga',
    cadastralRef: '2272102UF7627S0007KX',
    purchaseEuros: 39_500,
    valuationEuros: 92_000,
    salePriceEuros: 99_000,
    status: 'desocupado',
    details: 'Piso · 84 m² vivienda · 3 hab · 2 baños · sin ascensor',
    notes: 'Edificio mafia okupa.',
  }),
  build({
    id: 'F2-COS1-11',
    address: 'Calle Poniente 66',
    locality: 'Coslada',
    province: 'Madrid',
    cadastralRef: '4457119VK5745N0001AT',
    purchaseEuros: 110_000,
    valuationEuros: 170_000,
    salePriceEuros: 200_000,
    status: 'en_proceso_desocupacion',
    details: 'Casa · 173 m² vivienda · 4 hab · 1 baño · 1955 · parcela utilizable de 85 m²',
    notes: 'Valleaguado - La Cañada. Zona conflictiva (venta de droga). Referencia: en 2025 se vendió una en 142.000€ en peor estado.',
  }),
  build({
    id: 'F2-POL1-12',
    address: 'Calle Pelayo 12, Planta Baja',
    locality: 'Santa Pola',
    province: 'Alicante',
    cadastralRef: null,
    purchaseEuros: 52_316,
    valuationEuros: 128_000,
    salePriceEuros: null,
    status: 'listo_firma_arras',
    details: 'Planta baja de adosado · 101 m² vivienda + 2 m² parcela · 2 hab · 1 baño · 1967',
    notes: 'Pendiente arras con ocupantes actuales (tramitando hipoteca). Comprometidos: Juan Vicente González Carrillo y Carmen Botella. Precio pactado: 128.000€.',
  }),
  build({
    id: 'F2-POL2-13',
    address: 'Calle Taibilla 3, Esc. 1, 3º 2',
    locality: 'Santa Pola',
    province: 'Alicante',
    cadastralRef: '4107603YH1340N0008MF',
    purchaseEuros: 47_560,
    valuationEuros: 92_000,
    salePriceEuros: 98_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 83 m² vivienda · 3 hab · 2 baños · sin ascensor · 1974',
    dataQuality: [DATA_QUALITY_FLAGS.addressMismatchTabillanTaibilla],
  }),
  build({
    id: 'F2-CAS1-14',
    address: 'Avenida de María Auxiliadora 2, 1º B',
    locality: 'Vinarós',
    province: 'Castellón',
    cadastralRef: '5937201BE8853F0006KM',
    purchaseEuros: 100_000,
    valuationEuros: 140_000,
    salePriceEuros: 150_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 116 m² vivienda · 4 hab · 2 baños · con ascensor · patio · 1982',
    notes: 'Testigos: idealista 110491705, 110476244, 110474147.',
    dataQuality: [DATA_QUALITY_FLAGS.statusConflictMariaAuxiliadora],
  }),
  build({
    id: 'F2-CAS2-15',
    address: 'Calle Montebello 2, 2º',
    locality: 'Castellón',
    province: 'Castellón',
    cadastralRef: null,
    purchaseEuros: 39_335,
    valuationEuros: null,
    salePriceEuros: null,
    status: 'pendiente_de_compra',
    details: null,
    notes: 'Pendiente de compra. Costo es precio negociado; aún no se ha desembolsado capital. Sin valoración de Hernán.',
  }),
  build({
    id: 'F2-CAS3-16',
    address: 'Calle Virgen de la Paloma 17, Esc. 1, 3º 3',
    locality: 'Burriana',
    province: 'Castellón',
    cadastralRef: '9594707YK4199S0004QO',
    purchaseEuros: 25_158,
    valuationEuros: 55_000,
    salePriceEuros: 61_000,
    status: 'en_proceso_desocupacion',
    details: '84 m² vivienda · 3 hab · 1 baño · sin ascensor · 1969',
    notes: 'Testigo: https://www.idealista.com/inmueble/106246002/',
  }),
  build({
    id: 'F2-CAS4-17',
    address: 'Calle Virgen de Fátima 56',
    locality: 'Castellón',
    province: 'Castellón',
    cadastralRef: null,
    purchaseEuros: 20_894,
    valuationEuros: null,
    salePriceEuros: null,
    status: 'pendiente_de_compra',
    details: null,
    notes: 'Pendiente de compra. Costo es precio negociado; aún no se ha desembolsado capital. Sin valoración de Hernán.',
  }),
  build({
    id: 'F2-ZAR1-18',
    address: 'Avenida de América 32, 4º Dcha.',
    locality: 'Zaragoza',
    province: 'Zaragoza',
    cadastralRef: '6110508XM7161A0009XQ',
    purchaseEuros: 42_312,
    valuationEuros: 82_000,
    salePriceEuros: 90_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 64 m² vivienda · 2 hab · 1 baño · sin ascensor',
    notes: 'Testigo: https://www.idealista.com/inmueble/111106876/',
    dataQuality: [DATA_QUALITY_FLAGS.statusConflictAvenidaAmerica],
  }),
  build({
    id: 'F2-ZAR2-19',
    address: 'Gr. Mistral Gabriela 3, Esc. G, 2º Dcha.',
    locality: 'Zaragoza',
    province: 'Zaragoza',
    cadastralRef: '2534804XM7123D0005ML',
    purchaseEuros: 37_720,
    valuationEuros: 80_000,
    salePriceEuros: 90_000,
    status: 'en_proceso_desocupacion',
    details: '53 m² vivienda · 1 hab · 1 baño · sin ascensor · 1956',
    notes: 'Testigo: https://www.idealista.com/inmueble/111235495/',
  }),
  build({
    id: 'F2-VAL1-20',
    address: 'Calle Nou 24, Principal',
    locality: 'Catadau',
    province: 'Valencia',
    cadastralRef: '9704733YJ0590S0001RJ',
    purchaseEuros: 35_072,
    valuationEuros: 45_000,
    salePriceEuros: 52_000,
    status: 'desocupado',
    details: '66 m² vivienda + 28 m² almacén planta calle + 85 m² almacén 1º · 1971',
    notes: 'Testigo: https://www.idealista.com/inmueble/109910112/',
  }),
  build({
    id: 'F2-VAL2-21',
    address: 'Calle Villena 4, 3º A',
    locality: 'Elda',
    province: 'Alicante',
    cadastralRef: '2016604XH9621N0007BT',
    purchaseEuros: 21_106,
    valuationEuros: 46_000,
    salePriceEuros: 53_000,
    status: 'en_proceso_desocupacion',
    details: '71 m² vivienda · 2 hab · 1 baño · sin ascensor · 1960',
    notes: 'Testigos: idealista 110814475, 108462209.',
  }),
  build({
    id: 'F2-VAL3-22',
    address: 'Calle Magallanes 7, Bajo',
    locality: 'Alzira',
    province: 'Valencia',
    cadastralRef: '2477125YJ2327N0001DX',
    purchaseEuros: 7_995,
    valuationEuros: 50_000,
    salePriceEuros: 56_000,
    status: 'en_proceso_desocupacion',
    details: 'Adosado · 139 m² (77 m² vivienda + resto aparcamiento) + 32 m² parcela · 3 hab · 1 baño · 1920',
    notes: 'Testigo: https://www.idealista.com/inmueble/109668813/',
  }),
  build({
    id: 'F2-ALI1-23',
    address: 'Calle Colonia Santa Isabel 39, 1º Dcha.',
    locality: 'Alicante',
    province: 'Alicante',
    cadastralRef: null,
    purchaseEuros: 33_366,
    valuationEuros: null,
    salePriceEuros: null,
    status: 'pendiente_de_compra',
    details: null,
    notes: 'Pendiente de compra. Costo es precio negociado; aún no se ha desembolsado capital. Sin valoración de Hernán.',
  }),
  build({
    id: 'F2-JER1-24',
    address: 'Calle del Palo Cortado 7, Esc. 1, 4º D',
    locality: 'Jerez de la Frontera',
    province: 'Cádiz',
    cadastralRef: '5051504QA5655A0009AW',
    purchaseEuros: 26_240,
    valuationEuros: 60_000,
    salePriceEuros: 62_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 60 m² vivienda · 2 hab · 1 baño · sin ascensor · 1962',
    notes: 'Santiago - Coronación.',
  }),
  build({
    id: 'F2-JER2-25',
    address: 'Calle Beato Juan Pecador 1, Esc. 1, 2º 15',
    locality: 'Jerez de la Frontera',
    province: 'Cádiz',
    cadastralRef: '4646201QA5644F0035PB',
    purchaseEuros: 22_263,
    valuationEuros: 60_000,
    salePriceEuros: 63_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 56 m² vivienda · 2 hab · 1 baño · sin ascensor · 1960',
    notes: 'Santiago - Coronación.',
  }),
  build({
    id: 'F2-HUE1-26',
    address: 'Calle Río Guadalquivir 3, Esc. 1, 3º A',
    locality: 'Huelva',
    province: 'Huelva',
    cadastralRef: '4057103PB8245N0007QH',
    purchaseEuros: 22_714,
    valuationEuros: 65_000,
    salePriceEuros: 72_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 55 m² vivienda · 2 hab · 1 baño · sin ascensor · 1961',
    notes: 'Nuevo Parque - Los Rosales - Tráfico Pesado.',
  }),
  build({
    id: 'F2-COR1-27',
    address: 'Calle Algeciras 27, Esc. 3, 4º C',
    locality: 'Córdoba',
    province: 'Córdoba',
    cadastralRef: '3425101UG4932N0019HT',
    purchaseEuros: 22_140,
    valuationEuros: 50_000,
    salePriceEuros: 55_000,
    status: 'en_proceso_desocupacion',
    details: 'Piso · 57 m² vivienda · 2 hab · 1 baño · sin ascensor · 1960',
  }),
  build({
    id: 'F2-COR2-28',
    address: 'Calle Motril 44, Escalera E, Bajo 2',
    locality: 'Córdoba',
    province: 'Córdoba',
    cadastralRef: null,
    purchaseEuros: 25_256,
    valuationEuros: null,
    salePriceEuros: 42_500,
    status: 'vendido',
    details: null,
    notes: 'Arras pagadas 10% (4.250€). Compradora: Rosario López Obrero. Firma de escrituras prevista mayo 2026.',
  }),
]
